name: PR‑E2E‑KinD‑Testkube
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read          # needed by checkout
  id-token: write         # for ghcr if you push images
jobs:
  ephemeral-agent-test:
    runs-on: ubuntu-latest       # free‑tier hosted runner
    timeout-minutes: 25          # protect your 2 000 free minutes
    steps:
    # 1 – Grab code ----------------------------------------------------------
    - uses: actions/checkout@v4

    # 2 – Spin cluster (KinD) -----------------------------------------------
    - uses: engineerd/setup-kind@v0.5.0              # :contentReference[oaicite:0]{index=0}
      with:
        version: v0.23.0         # update if needed
        name: pr-${{ github.run_id }}
        wait: 30s                # give kube‑api a moment to come up
        # example of a 2‑node cluster (uncomment if you need it)
        # config: |
        #   kind: Cluster
        #   apiVersion: kind.x-k8s.io/v1alpha4
        #   nodes:
        #   - role: control-plane
        #   - role: worker

    # 3 – Install Helm & kubectl are already present ------------------------
    - uses: azure/setup-helm@v4           # tiny fast action

    # 4 – Install Testkube CLI for Github Actions ---------------------------   
    - name: Setup Testkube CLI
      uses: kubeshop/setup-testkube@v1
      with:
        organization: tkcorg_0f382d90e81ea228
        environment: tkcenv_943fe797cb48b4d2
        token: ${{ secrets.TESTKUBE_TOKEN }}

    # 5 - Creating a floating runner within the KinD cluster
    - name: Provision ephemeral runner
      run: |
        testkube install runner github-action-runner-${{ github.run_id }} --create --env paris --namespace testkube

    # 6 – Register / trigger your Testkube workflows -------------------------
    - name: Kick off Testkube workflows
      run: |
         testkube run testworkflow pytest-junit \
         -f \
         --target name=github-action-runner-${{ github.run_id }} \
         --tag pull-request=PR-${{ github.run_id }}

    # 7 - upload artifacts to github action...? ------------------------------
    - name: Upload artifacts from workflow execution
      uses: actions/upload-test-report@v2
      with:
        path: artifacts/*.xml   :contentReference[oaicite:2]{index=2}
         
    # 7 – Cleanup and remove ephemeral runner in Testkube ---------------------
#    - name: Delete ephemeral runner
#      run: |         
#          testkube delete runner github-action-runner-${{ github.run_id }} \
#          --delete \
#          --no-uninstall
